### PR TITLE
junit update to 4.11 and TestRule implementation

### PR DESCRIPTION
**Pull request by jangalinski**
created NeedleTestRule implementing TestRule which allows use of
RuleChains.

### CODE REVIEW

**Comment by jangalinski** [comment]
This removes the annoying deprecated-warning on MethodRule and allows composition of rule chains by implementing the state-of-the-art TestRule interface.

**Comment by hwilming** [comment]
There is already a discussion on TestRule and MethodRule. MethodRules are no longer deprecated with JUnit Version 4.11. https://github.com/KentBeck/junit/issues/351

**Comment by jangalinski** [comment]
You are right about the deprecation (4.11 is part of this request). But still:  Only TestRules can be used with the http://kentbeck.github.com/junit/javadoc/4.10/org/junit/rules/RuleChain.html. I consider RuleChains to be quite powerful and would love to use them with needle.

**Comment by jangalinski** [comment]
I just noticed: I forgot to provide a TestRule for DatabaseRule as well. Are you planning to release soon? Otherwise, I would work on this over the next days ...

**Comment by hwilming** [comment]
Done!

**Comment by jangalinski** [comment]
nice!

**Pull request merged**
